Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2018-09, with the labels that each got.

#1367 Avoids empty deployment selector value in generated yaml resource
  CHANGELOG.md
  plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
Labels: 3.5.x

#1361 Fix #1308 : upgrade kubernetes client to support OpenShift 3.9 and Kubernetes 1.8/1.9
  core/src/main/java/io/fabric8/maven/core/config/VolumeType.java
  core/src/main/java/io/fabric8/maven/core/handler/DaemonSetHandler.java
  core/src/main/java/io/fabric8/maven/core/handler/DeploymentHandler.java
  core/src/main/java/io/fabric8/maven/core/handler/JobHandler.java
  core/src/main/java/io/fabric8/maven/core/handler/ReplicaSetHandler.java
  core/src/main/java/io/fabric8/maven/core/handler/StatefulSetHandler.java
  core/src/main/java/io/fabric8/maven/core/service/ApplyService.java
  core/src/main/java/io/fabric8/maven/core/util/OpenShiftDependencyResources.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesClientUtil.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java
  core/src/test/java/io/fabric8/maven/core/handler/DaemonSetHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/handler/DeploymentHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/handler/JobHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/handler/ReplicaSetHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/handler/StatefulSetHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/util/MergeResourceTest.java
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/WatchEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DebugEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ImageEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/NameEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/PodAnnotationEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/RevisionHistoryEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/TriggersAnnotationEnricher.java
  enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/TriggersAnnotationEnricherTest.java
  it/src/it/env-metadata/expected/kubernetes.yml
  it/src/it/registry-286/expected/kubernetes.yml
  it/src/it/revisionhistory/expected/kubernetes.yml
  it/src/it/simple-maven-issue-mgmt/expected/kubernetes.yml
  it/src/it/simple-maven-scm/expected/kubernetes.yml
  it/src/it/simple-with-route-flag-false/expected/kubernetes.yml
  it/src/it/simple-with-route-flag-true/expected/kubernetes.yml
  it/src/it/simple/expected/kubernetes.yml
  it/src/it/spring-boot/expected/kubernetes.yml
  it/src/it/vertx-default/expected/kubernetes.yml
  it/src/it/vertx-health-check/expected/kubernetes.yml
  parent/pom.xml
  plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java
  plugin/src/main/java/io/fabric8/maven/plugin/converter/ReplicSetOpenShiftConverter.java
  plugin/src/main/java/io/fabric8/maven/plugin/enricher/MetadataVisitor.java
  plugin/src/main/java/io/fabric8/maven/plugin/enricher/SelectorVisitor.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java
  plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
  watcher/standard/src/main/java/io/fabric8/maven/watcher/standard/DockerImageWatcher.java
Labels: 4.0.x, OpenShift

#1381 fix(#1372): Set Kind/Filename mapping as AsciiDoc file
  CHANGELOG.md
  core/pom.xml
  core/src/main/java/io/fabric8/maven/core/util/AsciiDocParser.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KindFilenameMapperUtil.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java
  core/src/main/resources/META-INF/fabric8/kind-fileindicator-mapping-default.adoc
  core/src/test/java/io/fabric8/maven/core/util/AsciiDocParserTest.java
  core/src/test/java/io/fabric8/maven/core/util/kubernetes/KindFilenameMapperUtilTest.java
  core/src/test/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtilTest.java
  doc/pom.xml
  doc/src/main/asciidoc/inc/_appendix.adoc
  doc/src/main/asciidoc/index.adoc
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ProjectEnricher.java
  parent/pom.xml
  plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
Labels: pr/4.0

#1384 Fix #1383 check if casting to OpenshiftClient is possible.
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/access/ClusterAccess.java
  core/src/main/java/io/fabric8/maven/core/service/Fabric8ServiceHub.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/OpenshiftHelper.java
Labels: pr/4.0, pr/changelog-entry-please, pr/needs-backport

#1395 Fix #1365: Generated image reference in *-deployment.yml contains duplicate registry name
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java
  core/src/test/java/io/fabric8/maven/core/handler/ContainerHandlerTest.java
  core/src/test/java/io/fabric8/maven/core/handler/PodTemplateHandlerTest.java
  it/src/it/docker-health-checks/expected/kubernetes.yml
  it/src/it/docker-health-checks/expected/openshift.yml
  samples/xml-config/pom.xml
Labels: pr/4.0, pr/needs-backport

#1398 Fix #1365: Remove duplicate image reference in *-deployment.yml.
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java
  core/src/test/java/io/fabric8/maven/core/handler/ContainerHandlerTest.java
  samples/xml-config/pom.xml
Labels: cat/bug, pr/3.5
