Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2018-08, with the labels that each got.

#1345 feature: Update default base images to their latest versions
  parent/pom.xml
  samples/spring-boot-with-yaml/pom.xml
Labels: 3.5.x

#1348 Minor Changes in Jenkinsfile to avoid updating downstream dependencies
  CHANGELOG.md
  Jenkinsfile
  README.md
Labels: 3.5.x, 4.0.x

#1347 Support repackaged maven plugins for Karaf
  CHANGELOG.md
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/IconEnricher.java
  generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java
Labels: 3.5.x

#1344 feature: Remove unneeded Mojos
  CHANGELOG.md
  doc/src/main/asciidoc/inc/goals/_goals.adoc
  doc/src/main/asciidoc/inc/goals/build/_fabric8-app-catalog.adoc
  doc/src/main/asciidoc/inc/goals/build/_fabric8-distro.adoc
  doc/src/main/asciidoc/inc/goals/build/_fabric8-helm.adoc
  doc/src/main/asciidoc/inc/goals/build/_goals.adoc
  doc/src/main/asciidoc/inc/goals/develop/_fabric8-run.adoc
  doc/src/main/asciidoc/inc/goals/develop/_fabric8-start.adoc
  doc/src/main/asciidoc/inc/goals/develop/_fabric8-stop.adoc
  doc/src/main/asciidoc/inc/goals/develop/_goals.adoc
  doc/src/main/asciidoc/inc/goals/infra/_fabric8-cluster-start.adoc
  doc/src/main/asciidoc/inc/goals/infra/_fabric8-cluster-stop.adoc
  doc/src/main/asciidoc/inc/goals/infra/_fabric8-install.adoc
  doc/src/main/asciidoc/inc/goals/infra/_fabric8-setup.adoc
  doc/src/main/asciidoc/inc/goals/infra/_goals.adoc
  doc/src/main/asciidoc/inc/goals/internal/_fabric8-helm-index.adoc
  doc/src/main/asciidoc/inc/goals/internal/_fabric8-import.adoc
  doc/src/main/asciidoc/inc/goals/internal/_fabric8-manifest-index.adoc
  doc/src/main/asciidoc/inc/goals/internal/_goals.adoc
  doc/src/main/asciidoc/inc/goals/shortcut/_goals.adoc
  it/src/it/docker-compose/invoker.properties
  it/src/it/vertx/pom.xml
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AbstractResourceMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/AppCatalogMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/DistroMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/AbstractTailLogMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/LogMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/RunMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/StartMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/StopMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/AbstractInstallMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/ClusterStartMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/ClusterStopMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/InstallMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/infra/SetupMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/AbstractArtifactSearchMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/HelmIndexMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ManifestIndexMojo.java
  plugin/src/test/java/io/fabric8/maven/plugin/HelmEscapeTest.java
  plugin/src/test/java/io/fabric8/maven/plugin/enricher/EnricherManagerTest.java
Labels: 4.0.x, Refactoring, WIP

#1214 feature: Don't use a default for skipBuildPom
  CHANGELOG.md
  doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java
Labels: 4.0.x

#1351 Upgrade Jgit to version 5.0.2.201807311906-r
  parent/pom.xml
Labels: 3.5.x, 4.0.x

#1270 Changes the timestamp tag to latest for Docker Images
  CHANGELOG.md
  generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java
  generator/api/src/test/java/io/fabric8/maven/generator/api/support/BaseGeneratorTest.java
Labels: 4.0.x
