Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2018-07, with the labels that each got.

#1167 support for docker.pull.registry
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java
  core/src/test/java/io/fabric8/maven/core/handler/ContainerHandlerTest.java
Labels: waiting on feedback

#1336 fix(base-images): Update to s2i 2.2
  CHANGELOG.md
  parent/pom.xml
Labels: 3.5-x

#1152 Java EE 8 sample (IBM WebSphere Liberty is used as a Java EE 8 implementation)
  samples/javaee8-webprofile-liberty/.github/integration-test-successfully-run.png
  samples/javaee8-webprofile-liberty/README.md
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app-it/pom.xml
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app-it/src/test/java/io/fabric8/maven/sample/javaee/webprofile/integration/test/MeetingBookingServiceIT.java
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/pom.xml
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/java/io/fabric8/maven/sample/javaee/webprofile/MeetingBookingApplication.java
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/java/io/fabric8/maven/sample/javaee/webprofile/service/MeetingBookingService.java
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/java/io/fabric8/maven/sample/javaee/webprofile/servlet/DemoServlet.java
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/webapp/META-INF/MANIFEST.MF
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/webapp/WEB-INF/beans.xml
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/wlp/bootstrap.properties
  samples/javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/src/main/wlp/server.xml
  samples/javaee8-webprofile-liberty/pom.xml
Labels: 3.5-x, Feedback required

#1337 Small doc improvements
  doc/src/main/asciidoc/inc/_introduction.adoc
  doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc
Labels: 3.5.x

#1339 Add more details info related to liveness and readiness probes HTTPS
  doc/src/main/asciidoc/inc/generator/_spring_boot.adoc
Labels: 3.5.x

#1321 Fix #1312 : Container name should not be generated from maven group Id
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java
  core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java
Labels: 3.5.x

#1318 Fix #1299 : autotls feature doesn't work with OpenShift 3.9 (Kubernetes 1.8+) due to InitContainer annotation deprecation
  CHANGELOG.md
  enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/InitContainerHandler.java
  enricher/api/src/test/java/io/fabric8/maven/enricher/api/util/InitContainerHandlerTest.java
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/AutoTLSEnricher.java
  enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AutoTLSEnricherTest.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricher.java
  enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricherTest.java
  it/src/it/deployment-strategy-type-919/expected/kubernetes.yml
  it/src/it/deployment-strategy-type-919/verify.groovy
  it/src/it/volume-enricher-custom-storage-class/expected/kubernetes.yml
  it/src/it/volume-enricher-custom-storage-class/verify.groovy
  it/src/it/volume-enricher-storage-class-835/expected/kubernetes.yml
  it/src/it/volume-enricher-storage-class-835/verify.groovy
Labels: 3.5.x

#917 Allow configurable timeoutSeconds for SpringBootHealthCheckEnricher
  CHANGELOG.md
  doc/src/main/asciidoc/inc/_enricher.adoc
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/SpringBootHealthCheckEnricher.java
  enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractSpringBootHealthCheckEnricherSupport.java
Labels: 3.5.x

#1074 Preserve file extension when copying the file to helm chart folder
  CHANGELOG.md
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java
Labels: 3.5.x

#1341 spring-boot-maven-plugin is detected under any groupId
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/util/MavenUtil.java
  core/src/main/java/io/fabric8/maven/core/util/SpringBootConfigurationHelper.java
  generator/spring-boot/src/main/java/io/fabric8/maven/generator/springboot/SpringBootGenerator.java
  generator/spring-boot/src/test/java/io/fabric8/maven/generator/springboot/SpringBootGeneratorTest.java
  watcher/standard/src/main/java/io/fabric8/maven/watcher/standard/SpringBootWatcher.java
Labels: 3.5.x
