Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2019-03, with the labels that each got.

#1499 Fix #931: Add ServiceAccount enricher and configuration
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java
  core/src/main/java/io/fabric8/maven/core/config/ServiceAccountConfig.java
  doc/src/main/asciidoc/inc/_enricher.adoc
  doc/src/main/asciidoc/inc/_introduction.adoc
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ServiceAccountEnricher.java
  enricher/standard/src/main/resources/META-INF/fabric8/enricher-default
  enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/ServiceAccountEnricherTest.java
  plugin/src/main/resources/META-INF/fabric8/profiles-default.yml
Labels: pr/waiting-on-feedback

#1202 Improve support for sidecar containers
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/handler/DeploymentConfigHandler.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java
  doc/src/main/asciidoc/inc/_enricher.adoc
  enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java
  enricher/api/src/main/java/io/fabric8/maven/enricher/api/EnricherContext.java
  enricher/api/src/main/java/io/fabric8/maven/enricher/api/MavenEnricherContext.java
  enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/AbstractHealthCheckEnricher.java
  enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractHealthCheckEnricherTest.java
  enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/DockerHealthCheckEnricherTest.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java
  it/src/it/sidecar/expected/kubernetes.yml
  it/src/it/sidecar/expected/openshift.yml
  it/src/it/sidecar/invoker.properties
  it/src/it/sidecar/pom.xml
  it/src/it/sidecar/src/main/fabric8/deployment.yml
  it/src/it/sidecar/src/main/java/zero/Application.java
  it/src/it/sidecar/src/main/java/zero/HelloController.java
  it/src/it/sidecar/verify.groovy
  plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java
Labels: pr/waiting-on-feedback, target/4.0

#1602 Added documentation regarding new behavior for resource fragments when using sidecars
  CHANGELOG.md
  doc/src/main/asciidoc/inc/_introduction.adoc
Labels: cat/documentation
