Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2019-01, with the labels that each got.

#1466 Allow to configure noCache option for openshift docker build strategy
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
  core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java
Labels: pr/changelog-entry-please

#1476 stringData secret should be checked during patching as well
  core/src/main/java/io/fabric8/maven/core/service/PatchService.java
  core/src/test/java/io/fabric8/maven/core/service/openshift/PatchServiceTest.java
Labels: pr/changelog-entry-please

#1467 Wait timeout for build pod is too small
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java
Labels: pr/changelog-entry-please

#1487 Fix #925: Unable to configure replicas count via property
  CHANGELOG.md
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
Labels: cat/bug, pr/waiting-on-feedback

#1491 feat(#804): Allow set fragments as external references (URL)
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java
  core/src/main/java/io/fabric8/maven/core/util/FileUtil.java
  doc/src/main/asciidoc/inc/goals/build/_fabric8-resource.adoc
  it/src/it/remote-resources/expected/kubernetes.yml
  it/src/it/remote-resources/expected/openshift.yml
  it/src/it/remote-resources/invoker.properties
  it/src/it/remote-resources/pom.xml
  it/src/it/remote-resources/src/main/java/io/vertx/example/SimpleWebVerticle.java
  it/src/it/remote-resources/verify.groovy
  plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java
Labels: group/fragments, pr/waiting-on-feedback

#1465 Fix #1356: Updated compatibility matrix with latest kubernetes/Openshift versions
  README.md
Labels: cat/documentation
