Repository fabric8io/fabric8-maven-plugin, pull requests merged in 2019-07, with the labels that each got.

#1661 Added ResourceVersioning support for RBAC
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/util/ResourceVersioning.java
  core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java
Labels: jshift/pending

#1643 added service port normalization
  CHANGELOG.md
  core/src/main/java/io/fabric8/maven/core/config/ServiceConfig.java
  doc/src/main/asciidoc/inc/_enricher.adoc
  doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java
  enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricherTest.java
Labels: jshift/pending

#1660 Chore: Minor refactor to avoid code duplication.
  CHANGELOG.md
  enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ControllerViaPluginConfigurationEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java
  enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/ImageChangeTriggerEnricher.java
Labels: jshift/pending

#1671 Updated compatibility tables
  doc/src/main/asciidoc/inc/_compatibility.adoc
Labels: jshift/pending, pr/changelog-entry-please

#1672 Removed redundant profiles.
  CHANGELOG.md
  parent/pom.xml
Labels: jshift/pending

#1652 added Java11 base images for docker builds
  CHANGELOG.md
  doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc
  enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/ThorntailV2HealthCheckEnricherTest.java
  generator/api/src/main/java/io/fabric8/maven/generator/api/FromSelector.java
  generator/api/src/main/resources-filtered/META-INF/fabric8/default-images.properties
  generator/api/src/test/java/io/fabric8/maven/generator/api/FromSelectorTest.java
  generator/api/src/test/resources/META-INF/fabric8/default-images.properties
  generator/java-exec/src/test/java/io/fabric8/maven/generator/javaexec/JavaRunGeneratorTest.java
  parent/pom.xml
  samples/spring-boot-with-yaml/pom.xml
Labels: cat/feature, jshift/pending
